### ISSUE TITLE
The circuit can be smaller.  :)

### ISSUE THREAD

**Issue by idolpx** [JanDerogee/IEC-serial-RSS-feed-printer#1]
There is no need for the level shifting.  It's always nice to eliminate unnecessary components.
The ESP8266 I/O lines are 5v tolerant (Confirmed by Espressif CEO) and work just fine directly wired to the IEC serial port. 
I've been using them directly wired for a few years with no issues.
Nice project.  I love seeing new ways to use retro systems.

**Comment by JanDerogee** [comment]
Ok, thanks for the tip. I wasn't sure about the 5v tolerant io. Though the transistors don't hurt, it's always nice to know a circuit can be simplified safely.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
From: idolpx ***@***.***>
Sent: Wednesday, May 4, 2022 6:55:52 AM
To: JanDerogee/IEC-serial-RSS-feed-printer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JanDerogee/IEC-serial-RSS-feed-printer] The circuit can be smaller. :) (Issue #1)


There is no need for the level shifting. It's always nice to eliminate unnecessary components.
The ESP8266 I/O lines are 5v tolerant (Confirmed by Espressif CEO) and work just fine directly wired to the IEC serial port.
I've been using them directly wired for a few years with no issues.
Nice project. I love seeing new ways to use retro systems.
